name: Test
on:
  pull_request:
    types: [review_requested]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Run Action
        uses: ./
        id: buddy-review-assigner-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
